name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: '12.4.0'
      
    - name: Run unit tests
      run: xcodebuild test -scheme gu -workspace gu.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' | xcpretty && exit ${PIPESTATUS[0]}
